name: ci build

on: push

jobs:
  first-job:
    runs-on: windows-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: php --version

  release-project:
    name: Release project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          # generate_release_notes: true