name: ci build

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  build:
    name: PHP ${{ matrix.php-versions }}
    runs-on: ubuntu-latest
    if: (! contains(github.event.head_commit.message, '[ci skip]'))

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.1']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP Action
        uses: shivammathur/setup-php@v2
        with:
          extensions: intl, json, mbstring, xdebug, xml
          php-version: "${{ matrix.php-versions }}"
          tools: composer
          coverage: xdebug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: "Validate composer.json and composer.lock"
        run: "composer validate"

      - name: Install dependencies
        run: |
          if [ -f composer.lock ]; then
            composer install --no-progress --no-interaction --prefer-dist --optimize-autoloader
          else
            composer update --no-progress --no-interaction --prefer-dist --optimize-autoloader
          fi
          
      - name: "Run test suite"
        run: "composer test"
