name: Jays first test yam written nov 20

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  jay-build:
    runs-on: ubuntu-latest
    steps:
      - run: node --version
      - run: npm --version
      - run: php --version